---
# Dnsmasq
dnsmasq_interface: "ens8"
router_ip: "192.168.10.1"
netmask: "255.255.255.0"
dns_server: "192.168.10.1"
dhcp_range: "192.168.10.100,192.168.10.200,12h"

# TFTP directory
tftpboot_dir: "/var/www/tftpboot"

# ISO directory
iso_dir: "/var/www/iso"
