---
- name: Create bios and ipxe directory
  file:
    path: "{{ tftpboot_dir }}/{{ item }}"
    state: directory
    recurse: true
    mode: '0755'
  loop:
    - "bios/pxelinux.cfg"
    - "ipxe"
  tags:
    - boot_menu_conf

- name: Create symlink for bios/pxelinux.0
  file:
    src: "/usr/lib/PXELINUX/pxelinux.0"
    dest: "{{ tftpboot_dir }}/bios/pxelinux.0"
    state: link
  tags:
    - boot_menu_conf

- name: Create symlink for bios/ldlinux.c32
  file:
    src: "/usr/lib/syslinux/modules/bios/ldlinux.c32"
    dest: "{{ tftpboot_dir }}/bios/ldlinux.c32"
    state: link
  tags:
    - boot_menu_conf

- name: Create symlink for bios/menu.c32
  file:
    src: "/usr/lib/syslinux/modules/bios/menu.c32"
    dest: "{{ tftpboot_dir }}/bios/menu.c32"
    state: link
  tags:
    - boot_menu_conf

- name: Create symlink for bios/libutil.c32
  file:
    src: "/usr/lib/syslinux/modules/bios/libutil.c32"
    dest: "{{ tftpboot_dir }}/bios/libutil.c32"
    state: link
  tags:
    - boot_menu_conf

- name: Create symlink for bios/memdisk
  file:
    src: "/usr/lib/syslinux/memdisk"
    dest: "{{ tftpboot_dir }}/bios/memdisk"
    state: link
  tags:
    - boot_menu_conf

- name: Create symlink for ipxe/ipxe.efi
  file:
    src: "/usr/lib/ipxe/ipxe.efi"
    dest: "{{ tftpboot_dir }}/ipxe/ipxe.efi"
    state: link
  tags:
    - boot_menu_conf
